version: '1.0'
services:
  weaviate:
    image: semitechnologies/weaviate:latest
    ports:
      - "8080:8080"
    environment:
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: /var/lib/weaviate/data
      ENABLE_MODULES: text2vec-openai
      DEFAULT_VECTORIZER_MODULE: text2vec-openai
      OPENAI_APIKEY: ${OPENAI_API_KEY}
      OPENAI_ORGANIZATION: ${OPENAI_ORGANIZATION}
    volumes:
      - weaviate-data:/var/lib/weaviate/data
    restart: always

  myapp:
    build: .
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - weaviate

volumes:
  weaviate-data: